---
- name: deployment
  hosts: all
  become: true
    
  tasks:
  - name: Download file from a file path
    ansible.builtin.get_url:
      url: "http://65.0.118.250:8081/repository/java-maven-war-app-release/com/mycompany/app/hello-world-war/2.0.1/hello-world-war-2.0.1.war"
      dest: /home/ec2-user
      username: admin
      password: bukber-govGe0-jigtax

  - name: Rename war file
    ansible.builtin.shell: mv /home/ec2-user/hello-world-war-2.0.1.war /home/ec2-user/faangler.war

  - name: Deploying artifact in webapps
    ansible.builtin.shell: cp /home/ec2-user/faangler.war /opt/apache-tomcat-9.0.95/webapps/faangler.war

  - name: remove the artifact
    ansible.builtin.shell: rm -rf /home/ec2-user/faangler.war
